apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: hello-world-  # Name of this Workflow
spec:
  entrypoint: test        # Defines "whalesay" as the "main" template
  templates:
  - name: test            # Defining the "whalesay" template
    dag:
      tasks:
      - name: a
        template: test-a
      - name: b
        dependencies: [a]
        template: test-b
      - name: c
        dependencies: [a]
        template: test-c
      - name: d
        dependencies: [b, c]
        template: test-d
  - name: test-a
    container:
      image: ubuntu
  - name: test-b
    container:
      image: ubuntu
  - name: test-c
    container:
      image: ubuntu
  - name: test-d
    container:
      image: ubuntu
